theme: minima
title: R User Group at Maastricht University (RUG@UM)
header_pages:
  - blog.md
  - schedule.md
  - materials.md
  - topics.md
  - members.md

#theme: jekyll-theme-cayman
#title:   RUG@UM
#tagline: R User Group at Maastricht University
