theme: minima
title: RUG@UM
author:
  name: Wolfgang Viechtbauer
  email: "wolfgang.viechtbauer@maastrichtuniversity.nl"
header_pages:
  - blog.md
  - schedule.md
  - materials.md
  - topics.md
  - members.md

#theme: jekyll-theme-cayman
#title:   RUG@UM
#tagline: R User Group at Maastricht University
